kafka:
  stream:
    topic-in: streaming-topic-in
    topic-out: streaming-topic-out
    filtering-topic-in: filtering-topic-in
    filtering-topic-out: filtering-topic-out
    branching-topic-in: branching-topic-in
    branching-even-topic: branching-even-topic
    branching-odd-topic: branching-odd-topic
spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      bootstrap-servers: localhost:9092
      application-id: kafka-stream
